-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 14:38:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eventsMolina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eventsMolina` ;

-- -----------------------------------------------------
-- Schema eventsMolina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventsMolina` DEFAULT CHARACTER SET utf8 ;
USE `eventsMolina` ;

-- -----------------------------------------------------
-- Table `eventsMolina`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventsMolina`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(25) NOT NULL,
  `paymentMode` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);

--
-- Dumping data for table `event`
--
LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` VALUES (1,CURRENT_TIMESTAMP,"Oscar","AGUDELO","oscar@oscar.com","$2a$10$aRPSaN/EajpkvdRVrT1hQeXyBWe.UvTcILLi6.TFgx.ihCCkYqkWC","0636172130",1);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `eventsMolina`.`playLists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventsMolina`.`playLists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `eventsMolina`.`guestsList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventsMolina`.`guestsList` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `eventsMolina`.`sponsorsList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventsMolina`.`sponsorsList` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `eventsMolina`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventsMolina`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `address` VARCHAR(255) NOT NULL,
  `time` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `date` VARCHAR(255) NOT NULL,
  `price` VARCHAR(255) NOT NULL,
  `logoURL` VARCHAR(255) NULL,
  `playLists_id` INT NULL,
  `guestsList_id` INT NULL,
  `sponsorsList_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_playLists1_idx` (`playLists_id` ASC) VISIBLE,
  INDEX `fk_events_guestsList1_idx` (`guestsList_id` ASC) VISIBLE,
  INDEX `fk_events_sponsorsList1_idx` (`sponsorsList_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_playLists1`
    FOREIGN KEY (`playLists_id`)
    REFERENCES `eventsMolina`.`playLists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_guestsList1`
    FOREIGN KEY (`guestsList_id`)
    REFERENCES `eventsMolina`.`guestsList` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_sponsorsList1`
    FOREIGN KEY (`sponsorsList_id`)
    REFERENCES `eventsMolina`.`sponsorsList` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
--
-- Dumping data for table `event`
--
LOCK TABLES `events` WRITE;
/*!40000 ALTER TABLE `events` DISABLE KEYS */;
INSERT INTO `events` VALUES (1,CURRENT_TIMESTAMP,'Av. Valencia, 33, 30500 Molina de Segura, Murcia','18:00','PENTECOSTÉS 2022','Primera edición...','2022-09-20','10,00€',NULL,NULL,NULL,NULL),(2,CURRENT_TIMESTAMP,'Próximamente','Próximamente','Pentecostés 2023','Próximamente...','2024','Próximamente',NULL,NULL,NULL,NULL),(3,CURRENT_TIMESTAMP,'Próximamente','Próximamente','Pentecostés 2024','Próximamente...','2024','Próximamente',NULL,NULL,NULL,NULL);
/*!40000 ALTER TABLE `events` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `eventsMolina`.`events_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventsMolina`.`events_has_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_events_has_users_events_idx` (`events_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_has_users_events`
    FOREIGN KEY (`events_id`)
    REFERENCES `eventsMolina`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eventsMolina`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;